name: 'Staging deploy'

on:
  push:
    branches:
      - dev

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to staging
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.GIT_REMOTE_URL_STAGING }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
